### ISSUE TITLE
建议把lodash lib升级到3.*版本

### ISSUE THREAD

**Issue by rendongsc** [fex-team/yog2-kernel#1]
对于lodash等引用频率很高的通用库，建议经常升级到最近版本，避免使用yog2时维护多个版本，谢谢！

**Comment by hefangshi** [comment]
大版本升级有什么修改？

**Comment by rendongsc** [comment]
增加了String常用方法等。

**Comment by hefangshi** [comment]
升级lodash到3.x遇到了很多问题，不仅仅是功能新增

1. _first和_last有了变更，是一个breaking change
2. _(obj).forEach不再支持object

这也是我们为什么不会追着依赖库升级，大版本升级成本经常会出乎意料的高。

**Comment by rendongsc** [comment]
周期性更新依赖的第三方库是大势所趋，遇到breaking change带来的问题也是正常的。任何一个开发者都是在不断否定自己中前进，非常感谢你们做了升级尝试！
yog2虽然star数不多，但是完全契合我们的开发理念，是我们理想的首选框架！
希望yog2经常保持更新，让我们享受更多的开发便利！
谢谢！

**Comment by hefangshi** [comment]
感谢支持

目前已经发布了0.3.6，我这边偶现了一次加载hang住10s的问题，但是不能复现，可能和express也升级了大版本有关，有空你可以试用看看，可能是其他因素导致的

**Comment by rendongsc** [comment]
好的！
